import joi from '@hapi/joi'

export const broadcastConfig = joi.object().keys({
  prefix: joi.string().allow('', null),
  live_mode: joi.boolean().required(),
  auto_save: joi.boolean().required(),
  auto_transaction: joi.boolean().required(),
  profile: joi.string().allow(null).required(),
  enabled: joi.boolean(),
  auto_queue: joi.boolean(),
  default_publish_timeout: joi.number().allow(null).required(),
  // profiles: joi.object().pattern(/^/, joi.array().items(joi.string().regex(/(.+)\.(.+)/))),
  profiles: joi.object().pattern(/^/, joi.array().items(joi.string())),
  exchange_name: joi.string().allow(null),
  connection: joi.object().keys({
    unique: joi.string().allow(null),
    exchange: joi.string().allow(null),
    work_queue_name: joi.string().allow(null),
    interrupt_queue_name: joi.string().allow(null),
    poison_queue_name: joi.string().allow(null),
    host: joi.string().allow(null),
    user: joi.string().allow(null),
    pass: joi.string().allow(null),
    port: joi.number().allow(null),
    vhost: joi.string().allow(null),
    uri: joi.string().allow(null),
    heartbeat: joi.number(),
    timeout: joi.number().allow(null),
    failAfter: joi.number(),
    retryLimit: joi.number()
  }).unknown(),
  broadcasters: joi.object(),
  projectors: joi.object(),
  processors: joi.object(),
  hooks: joi.object(),
  pipelines: joi.object(),
  channels: joi.object(),
})
